include: package:flutter_lints/flutter.yaml
analyzer:
    errors:
        use_build_context_synchronously: ignore
        library_prefixes: ignore
linter:
    rules:
        prefer_const_constructors: false
        prefer_const_literals_to_create_immutables: false
        valid_regexps: false
        always_declare_return_types: true
        prefer_const_constructors_in_immutables: false
        prefer_final_fields: false
        camel_case_types: false
        camel_case_extensions: false
        non_constant_identifier_names: false
        no_leading_underscores_for_local_identifiers: false
        library_annotations: true
        constant_identifier_names: false
        type_annotate_public_apis: true
        always_specify_types: true
        avoid_relative_lib_imports: true
        library_prefixes: false
        avoid_init_to_null: false
        avoid_web_libraries_in_flutter: false
        unnecessary_const: false
        file_names: false
        use_function_type_syntax_for_parameters: false
        library_private_types_in_public_api: false
        prefer_function_declarations_over_variables: false
        prefer_interpolation_to_compose_strings: false
